/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_monitorend_WVSSView */

#ifndef _Included_com_h264_decoder_HD264Decoder
#define _Included_com_h264_decoder_HD264Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_h264_decoder_HD264Decoder
 * Method:    InitDecoder
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_h264_decoder_HD264Decoder_InitDecoder
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_h264_decoder_HD264Decoder
 * Method:    UninitDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_h264_decoder_HD264Decoder_UninitDecoder
  (JNIEnv *, jobject);

/*
 * Class:     com_h264_decoder_HD264Decoder
 * Method:    DecodeNal
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_h264_decoder_HD264Decoder_DecodeNal
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
