cutImageArgs|[13,48,516,898]
workpath|monkeyrunner/png/
START_ACTIVITY|{'component':'com.uih.android.nurse/.activity.SplashActivity',}
RECORD_IMAGE|{'path':'SplashActivity','format':'png',}|[10,40,516,898]
TOUCH|{'x':21,'y':886,'type':'downAndUp',}
TOUCH|{'x':205,'y':520,'type':'downAndUp',}
TOUCH|{'x':507,'y':818,'type':'downAndUp',}
TOUCH|{'x':507,'y':818,'type':'downAndUp',}
TOUCH|{'x':507,'y':818,'type':'downAndUp',}
TOUCH|{'x':507,'y':818,'type':'downAndUp',}
TOUCH|{'x':507,'y':818,'type':'downAndUp',}
TOUCH|{'x':507,'y':818,'type':'downAndUp',}
TOUCH|{'x':507,'y':818,'type':'downAndUp',}
TOUCH|{'x':507,'y':818,'type':'downAndUp',}
TYPE|{'message':'FXL',}
TOUCH|{'x':501,'y':568,'type':'downAndUp',}
TOUCH|{'x':200,'y':578,'type':'downAndUp',}
TYPE|{'message':'123',}
TOUCH|{'x':440,'y':434,'type':'downAndUp',}
RECORD_IMAGE|{'path':'MainActivity','format':'png',}
TOUCH|{'x':123,'y':374,'type':'downAndUp',}
WAIT|{'seconds':1}
PRESS|{'name':'KEYCODE_MENU','type':'downAndUp',}
WAIT|{'seconds':1}
PRESS|{'name':'KEYCODE_BACK','type':'downAndUp',}
WAIT|{'seconds':1}
PRESS|{'name':'KEYCODE_BACK','type':'downAndUp',}
WAIT|{'seconds':1}
PRESS|{'name':'KEYCODE_BACK','type':'downAndUp',}
TOUCH|{'x':151,'y':552,'type':'downAndUp',}
WAIT|{'seconds':1}
PRESS|{'name':'KEYCODE_BACK','type':'downAndUp',}