/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xys_ecg_dataproc_EcgDataAnalysis */

#ifndef _Included_com_xys_ecg_dataproc_EcgDataAnalysis
#define _Included_com_xys_ecg_dataproc_EcgDataAnalysis
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xys_ecg_dataproc_EcgDataAnalysis_beAnalysisLength
#define com_xys_ecg_dataproc_EcgDataAnalysis_beAnalysisLength 60L
/*
 * Class:     com_xys_ecg_dataproc_EcgDataAnalysis
 * Method:    analysisInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xys_ecg_dataproc_EcgDataAnalysis_analysisInit
  (JNIEnv *, jclass);

/*
 * Class:     com_xys_ecg_dataproc_EcgDataAnalysis
 * Method:    analysis
 * Signature: ([B)Lcom/xys/ecg/bean/CDiagnoseResult;
 */
JNIEXPORT jobject JNICALL Java_com_xys_ecg_dataproc_EcgDataAnalysis_analysis
  (JNIEnv *, jobject, jbyteArray,jint,jint);

/*
 * Class:     com_xys_ecg_dataproc_EcgDataAnalysis
 * Method:    getIntCountFromJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xys_ecg_dataproc_EcgDataAnalysis_getIntCountFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
